update style and options parsing, change README to --help output

diff --git a/clearcache b/clearcache
--- a/clearcache
+++ b/clearcache
@@ -40,21 +40,24 @@ declare -A pkgs_v pkgs_c toremove_v toremove_c installed ignore
 
 usage() {
 cat <<'EOF'
-usage: clearcache [options] [targets]
+usage: clearcache [OPTIONS] [TARGET(S)]
+
+Selectively clears the pacman cache in /var/cache/pacman/pkg/. Keeps the two
+most recent versions of each package.
 
  Options:
   -h, --help          display this help menu
   -d, --dry           dry run, simply list targets instead of removing
   -q, --quiet         only prints filenames for -d/--dry or -l/--list-targets
   -f, --force         force removal of package files
-  -i, --ignore <pkg>  specify package(s) to ignore. this can be a comma
+  -i, --ignore PKG    specify package(s) to ignore. this can be a comma
                       separated list, or '-' reads a list from stdin, one
                       per line. can be used more than once.
-  -k, --keep <num>    specify number of old package files to keep. by default,
+  -k, --keep NUM      specify number of old package files to keep. by default,
                       clearcache will keep the two most recent versions.
   -l, --list-targets  list targets to remove, using PAGER/less, before 
                       removing. may not be used with -d/--dry
-  -t, --threads <num> use <num> threads. the default value is 5. using a
+  -t, --threads NUM   use NUM threads. the default value is 5. using a
                       large number will not gain you much, and is not 
                       recommended, but there is no hard limit.
   -u, --uninstalled   remove all package files for packages that are not
@@ -62,12 +65,10 @@ usage: clearcache [options] [targets]
                       specified number of old files for installed packages
   -v, --verbose       output more
 
-  there MUST be a space between the option and its argument.
-
  Targets:
-  targets are package names, as you would specify them to pacman.
-  if targets are specified, only package files belonging to them will be
-  removed. if no targets are specified, all packages except for thos
+  Targets are package names, as you would specify them to pacman.
+  If targets are specified, only package files belonging to them will be
+  removed. If no targets are specified, all packages except for those
   specified to be ignored will be removed.
 EOF
 }
@@ -90,11 +91,18 @@ parse() {
   bsdtar -O "$opts" "$1" .PKGINFO |
     awk -F '[[:blank:]]*=[[:blank:]]*' -v f="$1" '
       $1 == "pkgname" {printf("%s %s\n", f, $2); exit}' >&3
+
+  if ((${PIPESTATUS[0]})); then
+    printf 'bsdtar error file: %s\n' "$1" >&2
+    echo
+    return 1
+  fi
 }
 
 print_targets() {
   printf '%s\0' "${!toremove_c[@]}" | sort -z | while IFS= read -rd '' pkg; do
     ((!quiet)) && printf '%s:\n' "$pkg"
+
     for ((i=1; i<=toremove_c[$pkg]; i++)); do
       if ((quiet)); then
         printf '%s\n' "${toremove_v[$pkg,$i]}"
@@ -105,33 +113,57 @@ print_targets() {
   done
 }
 
-((UID == 0)) && {
+if ((UID == 0)); then
   printf '%s\n' 'do not run this as root, you will be prompted' >&2
   exit 1
-}
+fi
 
 {
-flock -n 9 || {
+if ! flock -n 9; then
   printf '%s\n' 'only one instance may be running at a time' \
                 "if you are sure that another instance isn't running,"
                 "remove '$lock_file'"
   exit 1
-}
+fi
 
+# option string, for short options.
+# very much like getopts, any option followed by a ':' takes a required arg
+optstring=hdqfi:k:lt:uv
+
+# iterate over options, breaking -ab into -a -b and --foo=bar into --foo bar
+# also turns -- into --endopts to avoid issues with things like wget -O-
 while (($#)); do
   case $1 in
+    # if option is of type -ab
     -[!-]?*)
+      # loop over each character starting with the second
       for ((i=1; i<${#1}; i++)); do
-        options+=(-"${1:i:1}")
+        c=${1:i:1}
+        
+        # add current char to options
+        options+=("-$c")
+
+        # if option takes a required argument, and it's not the last char
+        # make the rest of the string its argument
+        if [[ $optstring = *"$c:"* && ${1:i+1} ]]; then
+          options+=("${1:i+1}")
+          break
+        fi
       done
       ;;
+    # if option is of type --foo=bar, split on first '='
     --?*=*) options+=("${1%%=*}" "${1#*=}");;
-    --) options+=(--end);;
+    # add --endopts for --
+    --) options+=(--endopts);;
+    # otherwise, nothing special
     *) options+=("$1");;
   esac
+
   shift
 done
+# set new positional parameters to altered options
 set -- "${options[@]}"
+unset options
 
 while [[ $1 = -?* ]]; do
   case $1 in
@@ -143,26 +175,29 @@ while [[ $1 = -?* ]]; do
     -u|--uninstalled) uninst=1; shift;;
     -q|--quiet) quiet=1; shift;;
     -t|--threads)
-      [[ $2 != *[!0-9]* ]] && (($2 > 0)) || {
+      if [[ $2 = *[!0-9]* ]] || (($2 < 1)); then
         printf '%s\n' "invalid number of threads: '$2'" >&2
         exit 1
-      }
+      fi
+
       threads=$2
       shift 2
       ;;
     -k|--keep) 
-      [[ -z $2 || $2 = *[!0-9]* ]] && {
+      if [[ -z $2 || $2 = *[!0-9]* ]]; then
         printf '%s\n' "invalid number for -k: '$2'" >&2
         exit 1
-      }
+      fi
+
       tokeep=$2
       shift 2
       ;;
     -i|--ignore)
-      [[ $2 ]] || {
+      if [[ -z $2 ]]; then
         printf '%s\n' "must specify at least one package" >&2
         exit 1
-      }
+      fi
+
       if [[ $2 = - ]]; then
         if [[ -t 0 ]]; then
           printf '%s\n' "stdin is a terminal, no list was read" >&2
@@ -180,7 +215,7 @@ while [[ $1 = -?* ]]; do
       fi
       shift 2
       ;;
-      --end) shift; break;;
+      --endopts) shift; break;;
       *)
         printf '%s\n' "invalid option: '$1'" >&2
         exit 1
@@ -188,26 +223,31 @@ while [[ $1 = -?* ]]; do
   esac
 done
 
-((dry && list)) && {
+if ((dry && list)); then
   printf '%s\n' 'may not use both -d/--dry and -l/--list' >&2
   exit 1
-}
+fi
 
 targets=("$@")
 
-cd "$cachedir" || {
+if ! cd "$cachedir"; then
   printf '%s\n' "could not cd to '$cachedir'" >&2
   exit 1
-}
+fi
 
 if ((uninst)); then
-  ((v)) && printf '%s\n' "obtaining list of currently installed packages..."
+  if ((v)); then
+    printf '%s\n' "obtaining list of currently installed packages..."
+  fi
+
   while read -r pkg; do
     installed[$pkg]=1
   done < <(pacman -Qq)
 fi
 
-((v)) && printf '%s\n' "obtaining list of packages in '$cachedir'..."
+if ((v)); then
+  printf '%s\n' "obtaining list of packages in '$cachedir'..."
+fi
 
 if ((${#targets[@]})); then
   for t in "${targets[@]}"; do
@@ -218,21 +258,26 @@ else
 fi
 
 # now the fun starts
-mkfifo "$fifo" || {
+if ! mkfifo "$fifo"; then
   printf '%s\n' "couldn't create fifo '$fifo'" >&2
   exit 1
-}
+fi
+
 exec 3<>"$fifo"
 totfiles=${#files[@]}
 for ((curfile=0; curfile<threads; curfile++)); do
   ((curfile < totfiles)) && parse "${files[curfile]}" &
 done
+
 readfiles=0
 while read -r file pkg; do
   ((curfile < totfiles)) && parse "${files[curfile]}" &
-  ((ignore[$pkg])) || {
-    ((pkgs_c[$pkg]++)); pkgs_v[$pkg,${pkgs_c[$pkg]}]=$file
-  }
+
+  if [[ $file && $pkg ]] && ((! ignore[$pkg])); then
+    ((pkgs_c[$pkg]++))
+    pkgs_v[$pkg,${pkgs_c[$pkg]}]=$file
+  fi
+
   ((curfile++, ++readfiles == totfiles)) && break
 done <&3
 exec 3>&-
@@ -240,12 +285,14 @@ exec 3>&-
 ((v)) && printf '%s\n' "determining which packages to remove..."
 for pkg in "${!pkgs_c[@]}"; do
   ((pkgs_c[$pkg] > tokeep)) || continue
+
   {
     if ((!uninst || installed[$pkg])); then
       for ((i=0; i<tokeep; i++)); do
         read -d ''
       done
     fi
+
     while IFS= read -rd '' f; do
       ((toremove_c[$pkg]++, toremove_tot++))
       toremove_v[$pkg,${toremove_c[$pkg]}]=$f
@@ -256,12 +303,15 @@ for pkg in "${!pkgs_c[@]}"; do
         done | sort -Vrz)
 done
 
-((toremove_tot)) || {
+if ((!toremove_tot)); then
   printf '%s\n' "There is nothing to do."
   exit 1
-}
+fi
 
-((dry)) || printf '%s\n' "Removing '$toremove_tot' packages from '$cachedir'"
+if ((!dry)); then
+  printf '%s\n' "Removing '$toremove_tot' packages from '$cachedir'"
+fi
+
 if ((list)); then
   print_targets | ${PAGER:-less} 
 elif ((dry)); then
@@ -276,8 +326,8 @@ read -p 'Continue? [Y/n] ' reply >/dev/tty
 if ((force)); then
   runasroot rm -f "${toremove[@]}"
 else
-  runasroot rm "${toremove[@]}" || {
+  if ! runasroot rm "${toremove[@]}"; then
     printf '%s\n' "could not remove files" >&2
-  }
+  fi
 fi
 } 9>"$lock_file"
